version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./run/nginx:/run/nginx
    # other NGINX configurations...

  wordpress:
    build:
      context: ./wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
    volumes:
      - ./run/php:/run/php
    # other WordPress configurations...

  mariadb:
    build:
      context: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    # other MariaDB configurations...
